<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->

{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "Free Android games Adventure Based on 25 user ratings",
  "image" : "https://i1.wp.com/apkhome.net/wp-content/uploads/2018/01/Power-Hover-1.8.0.png?zoom=0.8999999761581421&resize=130%2C130&ssl=1",
  "url" : "http://wizwideweb.tk/",
  "author" : {
    "@type" : "Person",
    "name" : "Wisdom okon"
  },
  "datePublished" : "Please insert valid ISO 8601 date/time here. Examples: 2015-07-27 or 2015-07-27T15:30",
  "publisher" : {
    "@type" : "Organization",
    "name" : "Github.io"
  },
  "applicationCategory" : "games",
  "downloadUrl" : "http://wizwideweb.tk/",
  "operatingSystem" : "andriod",
  "requirements" : "nill",
  "screenshot" : "http://nill/",
  "softwareVersion" : "1.72",
  "aggregateRating" : {
    "@type" : "AggregateRating",
    "ratingValue" : "3.12%",
    "bestRating" : "3.5",
    "worstRating" : "0",
    "ratingCount" : "12"
  },
  "review" : {
    "@type" : "Review",
    "author" : {
      "@type" : "Person",
      "name" : "mike"
    },
    "datePublished" : "Please insert valid ISO 8601 date/time here. Examples: 2015-07-27 or 2015-07-27T15:30",
    "reviewRating" : {
      "@type" : "Rating",
      "ratingValue" : "3.5",
      "bestRating" : "3.5",
      "worstRating" : "0"
    },
    "reviewBody" : "nill"
  }
}
